@startuml
skinparam classAttributeIconSize 0

package CliView <<Folder>> {

    abstract class ControllerCli
    class InitialStageCli
    class SelectionStageCli
    class GameStageCli

    ControllerCli <|-- InitialStageCli
    ControllerCli <|-- SelectionStageCli
    ControllerCli <|-- GameStageCli

    class ControllerCli {
        # GameController gameController;
        # AtomicInteger returnValueIsOk;
        # Scanner scanner;

    }


}





@enduml